### ISSUE TITLE
Couldn't connect to http://raspiserver:800 - TypeError: e.response is undefined

### ISSUE THREAD

**Issue by FlipperLP** [neobooru/SzuruChrome#12]
I was unable to add my szuru server as i receive CORS errors in [Firefox](https://www.whatsmybrowser.org/b/K09D9).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://raspiserver:800/api/info. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://raspiserver:800/api/info. (Reason: CORS request did not succeed).

**Comment by FlipperLP** [comment]
ok.. my bad. rtfm

**Comment by FlipperLP** [comment]
So I have been on this for quite a while now, but I simply can't get it to work. Might be my missing knowledge about web servers in general and the missing information in the FAQ.
So I first tried using a nginx reverse-proxy, which partially worked, but the GET request still got blocked.
Then I researched a little and found out, that the configuration in the FAQ belongs to a .htaccess file? But where do I need to put that on my szurubooru installation. Or is that a browser thing I need to do?

**Comment by neobooru** [comment]
The configuration in the FAQ is for an Apache2 server. I haven't yet added a section for nginx.

Are you manually configuring NGINX, or are you using the official docker image? I didn't really test the docker image myself, so maybe there still is a bug with it.

[Official docker NGINX config](https://github.com/rr-/szurubooru/blob/master/client/nginx.conf.docker)
[My customized config (not for docker)](https://gist.github.com/neobooru/ff6e2bd3ec9e9ebd39a13e81e741fa8c)

The important part is the following snippet. Ideally you want this somewhere under `location /api/` (or a slight differentiation of that), but you can put it under the `server {...}` too (I think).
```nginx
# If pre-flight request
if ($request_method = "OPTIONS") {
    add_header "Access-Control-Allow-Origin" "*";
    add_header "Access-Control-Allow-Methods" "GET, POST, PUT, DELETE, OPTIONS";
    add_header "Access-Control-Allow-Headers" "Authorization, Content-Type";

    add_header "Access-Control-Max-Age" 1728000;
    return 204;
}

# For all other requests
add_header "Access-Control-Allow-Origin" "*";
add_header "Access-Control-Allow-Methods" "GET, POST, PUT, DELETE, OPTIONS";
add_header "Access-Control-Allow-Headers" "Authorization, Content-Type";
```

Please report back on what fixed your issue, or if this didn't fix it 👍

**Comment by FlipperLP** [comment]
Alright, we did it.
After I looked 3 Times on the same error message I noticed, that it's not allowed to have multiple `Access-Control-Allow-Origin`s. .-.
So I just commented the second `Access-Control-Allow-Origin` out and... it worked! Thank you a bunch!

[nginx config](https://hastebin.com/lapupezoxi.nginx)
[docker-compose](https://hastebin.com/noqejosohu.less)
