### ISSUE TITLE
Bug: GIF Upload - Error while processing image.

### ISSUE THREAD

**Issue by FlipperLP** [neobooru/SzuruChrome#13]
GIFs are not getting uploaded.

Response:

```json
{
  "name": "ProcessingError",
  "title": "Processing error",
  "description": "Error while processing image.\n"
}

**Comment by neobooru** [comment]
Could you provide a link to the website from where you want to import the image?
The tool currently works with a lot of site specific code, which is quite unstable. I'll also try to add a feature to manually specify which image you want to upload soon-ish (#14).

**Comment by FlipperLP** [comment]
I tested e621 and a direct link of different images.

**Comment by neobooru** [comment]
Hmm, that is weird. Do still/normal images work fine, and can you upload different GIFs just fine? On my end I was able to upload webm and gif animations from both e621 and direct links.
Also, how did you install this addon? On the release page there is a .xpi for firefox which is built from the latest version, though I assume that you already used this to install the addon.

**Comment by FlipperLP** [comment]
I used the release page. And Firefox does the rest with the "do you want to add this add-on".
I tried 3 different Gifs now, and it's still stuck at uploading. After a while I checked the debug log and there was the error.
WEBM don't get detected at all. 

I should mention, that I told szurubooru to convert the gifs into WEBMs (because I like to pause and stuff)

**Comment by FlipperLP** [comment]
Ok wait, on e6, WEBMs de get recognized, there is just no preview (Broken-Content Icon).
When I try to add it from a direct link it doesn't find it.

**Comment by neobooru** [comment]
Alright, I created issue #15 and #16 for that, not sure when I'll get around to fixing that.

Which means that the only remaining issue is that you can't upload gifs, right? I suppose this could have to do with the automatic conversion szurubooru does. I don't use that myself so that might be why I didn't notice any problems on my end.

**Comment by FlipperLP** [comment]
I'll disable it, recompile and try again.

**Comment by FlipperLP** [comment]
Yep... The conversion was the problem. Went through now
