### ISSUE TITLE
change request: use e621 source from info, instead of e621 link

### ISSUE THREAD

**Issue by FlipperLP** [neobooru/SzuruChrome#17]
Instead of using the e621 Link, use the source field in the post itself.
![image](https://user-images.githubusercontent.com/27019397/104517572-8a90e700-55f6-11eb-9e4a-9d8f9fef5eb5.png)

**Comment by neobooru** [comment]
This should now work in v0.5.0. You can always enable the old behavior (use current page url as source) on the options page. By default it uses the new system, where it uses the original source when available.
