### ISSUE TITLE
Bug/Feature: e926.net uses the same API as e621 but doesn't recognize tags

### ISSUE THREAD

**Issue by FlipperLP** [neobooru/SzuruChrome#19]
Maybe call the same function as for e621 (same API)

e921 is the SFW version of e921

**Comment by neobooru** [comment]
Do you mean e926? I can't find anything for e921.

**Comment by neobooru** [comment]
All sites are recognized by their URL, which means that each site has to be manually supported. I added support for e926.net in v5.0.1. Mozilla's Developer Portal is currently undergoing maintenance so I can't upload a new version at the moment (because Mozilla needs to sign it).

**Comment by neobooru** [comment]
Dev portal is back up, added an xpi for Firefox on the release page.
