### ISSUE TITLE
Feature: Option to sort tags in Category, if the same name in the suzu is found

### ISSUE THREAD

**Issue by FlipperLP** [neobooru/SzuruChrome#20]

**Comment by neobooru** [comment]
I don't quite understand this request? Do you want to sort the tags, or do you want to import a tag's category?

**Comment by FlipperLP** [comment]
Sort the tags in the category already set up in the szuru

**Comment by FlipperLP** [comment]
Well apparently this was already a thing for quite some time and I never noticed? Anyway I added the missing categories from e6 lore and the important species category.
https://github.com/neobooru/SzuruChrome/pull/25

**Comment by neobooru** [comment]
In the latest commit I changed it so that it only imports existing categories and I also merged your PR. So I guess this issue can be closed now?
