### ISSUE TITLE
Bug: Can't upload a WEBM animation from a direct link

### ISSUE THREAD

**Issue by FlipperLP** [neobooru/SzuruChrome#28]
The issue is sadly happening again/was never resolved.
I tested some older version, but the issue was still present

Old Issue: https://github.com/neobooru/SzuruChrome/issues/16

**Comment by neobooru** [comment]
My bad, apparently firefox does stuff different than chrome in that regard. Should be fixed in the newest version. If it happens again please feel free to reopen this issue.
