### ISSUE TITLE
Bug: error messages are no longer shown

### ISSUE THREAD

**Issue by FlipperLP** [neobooru/SzuruChrome#31]
In Firefox (not tested in other browsers) the error message is not shown, if something goes wrong, while uploading or updating the tags.

**Comment by FlipperLP** [comment]
They mostly happen with API errors, which are not handled otherwise. I was unable to reproduce it at the moment, but once I do ill make sure to send a screenshot.

**Comment by FlipperLP** [comment]
![image](https://user-images.githubusercontent.com/27019397/151930500-be09aa3b-f60e-411f-94e7-09a3d1d90126.png)

**Comment by neobooru** [comment]
I think I fixed this in the v0.8.0 release. Though feel free to reopen if it happens again.
