### ISSUE TITLE
Feature: Philomena based Boorus support

### ISSUE THREAD

**Issue by GlobalGit3** [neobooru/SzuruChrome#40]
Support for Philomena. Sites such as Furbooru, Derpibooru, and more use this for hosting their boorus.
https://github.com/philomena-dev/philomena

**Comment by GlobalGit3** [comment]
API Documentation here
https://derpibooru.org/pages/api

**Comment by GlobalGit3** [comment]
[Pull Request](https://github.com/neobooru/SzuruChrome/issues/41) on neo-scraper.

Will close this issue once merged and push to SzuruChrome.

**Comment by neobooru** [comment]
Support is added in the latest version ([v0.10.1](https://github.com/neobooru/SzuruChrome/releases/tag/v0.10.1)). Please reopen or create a new issue if there still are problems.
