### ISSUE TITLE
Feature: Pool Support

### ISSUE THREAD

**Issue by hujle** [neobooru/SzuruChrome#41]
A bit different request from #18, but it would be nice if the plugin could detect pools on the target board, and could add new post into desired pool right away.

**Comment by neobooru** [comment]
I assume that the pools need to have exactly the same name then?

**Comment by hujle** [comment]
By "target board" I meant the one you're uploading an image to. I'm looking for the possibility to add the image to already existing pool on the szurubooru instance.

**Comment by neobooru** [comment]
The latest version (v0.11) has a basic implementation of this feature. Please report back if you see room for improvement.
