### ISSUE TITLE
Tag category color recognition.

### ISSUE THREAD

**Issue by hujle** [neobooru/SzuruChrome#45]
While it can recognize classic tag categories that are present on the vast majority of the boorus, such as `artist`, `character`, `copyright`, `meta` and `default` one (all of these appears to be hard-coded into extension), it doesn't seem to be able to get tag color from other categories that might be present on the szurubooru instance you're uploading an image to.
For example, on my instance I have `effect` and `location` tag categories, but extension is unable to get the tag color of these categories and makes them just white color. It would be awesome if the extension could get the tag color from the non-standard tag categories.

**Comment by neobooru** [comment]
Would it also be okay if you could manually add categories and colors? So they wouldn't automatically appear and they would not be instance specific.

**Comment by hujle** [comment]
I don't think that's necessary, but sure, why not.

**Comment by neobooru** [comment]
Okay so I might've misunderstood the question, but the extension only imports the categories from whichever site is currently displayed. If you want to automatically import tags with the effect/location tag then that functionality needs to be added to the scraper for the site you want to import from (e.g. Zerochan or Gelbooru).

**Comment by hujle** [comment]
That's not what I'm asking for. I'm talking about tag category color recognition from the **szurubooru instance** you're uploading an image to. So like, if I would upload an image from, for example, Twitter, and I would want to apply the effect/location tag to the post - the tag would be colored with the color it has on the target szurubooru instance. Just like the most common tag categories are currently recognized and their tags getting colored when you're applying the tags before uploading.

**Comment by neobooru** [comment]
In the latest release (v0.10.3) you have to option to manually add tag categories. In a future update I'll add a button to automatically import the categories from a configured szurubooru instance.

**Comment by neobooru** [comment]
The 'import known categories' button has been added to the options page in v0.10.4.
