### ISSUE TITLE
Add feature to disable automatic tag import

### ISSUE THREAD

**Issue by neobooru** [neobooru/SzuruChrome#47]

**Comment by neobooru** [comment]
@hujle Do you just want an almighty toggle which disables tag importing for all sites? Or would you rather it be a toggle/blacklist for individual sites?

In response to https://github.com/neobooru/SzuruChrome/issues/45#issuecomment-1646693531

**Comment by hujle** [comment]
I'd rather have the toggle that disables tag importing from all sites.

**Comment by neobooru** [comment]
In the latest release (v0.10.3) there is a toggle on the options page which disables all automatic tag importing.
