### ISSUE TITLE
Gelbooru image import issue

### ISSUE THREAD

**Issue by bitcrusherrr** [neobooru/SzuruChrome#49]
I've noticed an error on [gelbooru](https://gelbooru.com/) 
Trying to import an image results in 403 error:
"Couldn't upload post. Download target returned HTTP 403. (Forbidden)"

SzuruChrome version 0.10.1.1
Tried on Edge, Vivaldi and Opera browsers.

**Comment by neobooru** [comment]
Have you changed the user agent to some 'legit' string in the server's config.yaml? That should fix the issue for most sites.

**Comment by bitcrusherrr** [comment]
Thank you that fixed it.
