### ISSUE TITLE
Incorrect behavior of extension after Twitter switching to x.com domain.

### ISSUE THREAD

**Issue by hujle** [neobooru/SzuruChrome#54]
I have noticed several examples of incorrect extension behavior while working with Twitter on it's new x.com domain.

For example, sometimes it fails to detect media completely:
![изображение](https://github.com/neobooru/SzuruChrome/assets/16465620/c36b4a5b-03dd-4ca7-aecc-1921b539693f)

Sometimes it picks up completely different image from "Discover more" section under original post:
![изображение](https://github.com/neobooru/SzuruChrome/assets/16465620/32c49c14-38f1-4d38-8786-2f91b0cc1772)

In this particular case, it couldn't find a full resolution image, which is 1850x1309 pixels, and picks up the smaller preview instead.
![изображение](https://github.com/neobooru/SzuruChrome/assets/16465620/a7dfab88-96e0-4385-8c34-4c6493fec86b)

And that's pretty much it for now. If I notice any other odd behavior - I'll update the issue.

**Comment by hujle** [comment]
Ok I see this issue has been fixed with the latest commit, but it would be great if you could release the new version of it with this fix in Firefox Add-ons. Thank you in advance.

**Comment by neobooru** [comment]
Sorry. kinda forgot about it. It is released on the store now.
