### ISSUE TITLE
Yande.re import fails with "Unhandled file type: 'application/octet-stream'"

### ISSUE THREAD

**Issue by G1org1owo** [neobooru/SzuruChrome#56]
I am not sure whether this is on the extension's end, on szurubooru's end or just because yande.re changed something about their images. I noticed when I tried to manually download the image from chrome I got a .htm file but wget could download the image with no problems at all.

**Comment by G1org1owo** [comment]
Moved to rr-/szurubooru#674

**Comment by neobooru** [comment]
The newest version of SzuruChrome now has a built-in workaround for this if you select "[fallback] Upload as content" in the combobox. This will currently not import tags, as those are never imported with the [fallback] importer. But I'll enable the fallback mechanic in the moebooru uploader, so it works by default (with tags etc).

The difference between "Import as URL" and "Import as content" is that the first sends the URL to szurubooru, and the second downloads the image locally in your browser and then uploads it on szurubooru. So the second (content) way is slower, but usually more compatible.

**Comment by G1org1owo** [comment]
I see, I had tried building the latest version but still got the same error so I ended up looking for a workaround in the server backend, didn't notice the new fallback option lol

On a side note, I'm pretty sure this is specifically a yande.re issue (because of strict referer policies and whatnot) rather than a moebooru one, I don't know if it's worth enabling "Import as content" by default for every moebooru instance.

**Comment by neobooru** [comment]
Alright. I was a bit confused because I though I had already fixed the issue, and turns out I did. So in SzuruChrome version [v0.12.2](https://github.com/neobooru/SzuruChrome/releases/tag/v0.12.2) this issue should've been resolved by default. So the default moebooru engine/uploader should work fine for yande,re
